// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rogdf_version
IntegerVector rogdf_version();
RcppExport SEXP OGDF_rogdf_version() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        IntegerVector __result = rogdf_version();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rogdf_circular_layout
NumericMatrix rogdf_circular_layout(GraphAttributes graph, double minDistCircle = 20, double minDistLevel = 20, double minDistSibling = 10, double minDistCC = 20, double pageRatio = 1);
RcppExport SEXP OGDF_rogdf_circular_layout(SEXP graphSEXP, SEXP minDistCircleSEXP, SEXP minDistLevelSEXP, SEXP minDistSiblingSEXP, SEXP minDistCCSEXP, SEXP pageRatioSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< GraphAttributes >::type graph(graphSEXP );
        Rcpp::traits::input_parameter< double >::type minDistCircle(minDistCircleSEXP );
        Rcpp::traits::input_parameter< double >::type minDistLevel(minDistLevelSEXP );
        Rcpp::traits::input_parameter< double >::type minDistSibling(minDistSiblingSEXP );
        Rcpp::traits::input_parameter< double >::type minDistCC(minDistCCSEXP );
        Rcpp::traits::input_parameter< double >::type pageRatio(pageRatioSEXP );
        NumericMatrix __result = rogdf_circular_layout(graph, minDistCircle, minDistLevel, minDistSibling, minDistCC, pageRatio);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
